image:
  - Visual Studio 2017
  - Ubuntu

configuration:
  - Release

platform:
  - x64

environment:
  DiscordNotificationWebHook:
    secure: 9ZFEBnW+lrCDIvInRHUN6L0kmoC062LJBBnRJlns4uLQ/x4V8zMoggQ2xMCi6bzwO6A+1Vo7vsEzv+YM6MVvrHNl0jjjnd8EeP75rBj7EkGrnJFveDmgHZREnE01N0S9oBYiHs6gkz7H5m/YUYHh+IDnk4T3/JC1JgzI0zqV/qE=

install:
  - sh: |
      sudo apt-get update
      sudo apt-get install -y libboost-all-dev qt5-default

before_build:
  - git submodule update --init --recursive

build_script:
  # setup c++ environment on windows
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

  # select cmake generator and boost version
  - ps: |
      $ErrorActionPreference = "Stop"
      if ($isLinux) {
        $CMakeGenerator = "Unix Makefiles"
        $CMakeBoostArg = ""
        $QtArgs = ""
      } else {
        $CMakeGenerator = "Visual Studio 15 2017 Win64"
        $CMakeBoostArg = "-DBOOST_ROOT=C:/Libraries/boost_1_67_0"
        $QtArgs = "-DCMAKE_PREFIX_PATH=C:/Qt/5.11.2/msvc2017_64"
      }

  # build process
  - ps: |
      New-Item -ItemType Directory -Force -Path .\.build  | Push-Location
      cmake `
        -G "$CMakeGenerator" `
        -DCMAKE_BUILD_TYPE=$configuration `
        -DCMAKE_INSTALL_PREFIX:PATH=../.install `
        $CMakeBoostArg $QtArgs `
        ..
      cmake --build . --config $configuration
      Pop-Location

on_success:
  - ps: ./scripts/ci/SendDiscordNotification.ps1 success $env:DiscordNotificationWebHook
on_failure:
  - ps: ./scripts/ci/SendDiscordNotification.ps1 failure $env:DiscordNotificationWebHook